spring:
  application:
    name: accountingsoftware
  datasource:

    url: jdbc:mysql://localhost:3306/accounting_db

    username: root

    password: "#Iamgood1"

    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:

    hibernate:

      ddl-auto: update

    show-sql: true

    properties:

      hibernate:

        format_sql: true


server:

  port: 8080
